= Documentation
:toc:

Want to make a faucet of your own?
link:https://www.000webhost.com/1021701.html[This site has good free PHP hosting!]

== Setup

 . On Faucet&nbsp;Hub&#700;s manager page, *make sure that the faucet is set up under the &ldquo;PTP&rdquo; and &ldquo;Mining&rdquo; categories*! If it isn&#700;t, users could get their accounts frozen for claiming too often!
 . Put everything in the document root of your site
 . Edit 'config.template.php', then rename it to 'config.php'
   - Every important setting is in 'config.php', so read it carefully!
   - If you don&#700;t know how to edit it, you probably shouldn&#700;t be running a faucet in the first place.
 . Rename the 'custom_templates/' directory to 'custom/', then edit the files inside of it
 . Everything should work now; get some people to claim from your faucet!
 . ???
 . PROFIT!!!

=== Updating the faucet

IMPORTANT: Moving to a different MAJOR version (such as from `3.x.x` to `4.x.x`) requires you to re-install the entire faucet script from scratch. Do not attempt to update in-place.

For minor updates (such as from 1.2.0 to 1.3.0):

 - Read the release description for any special instructions
 - Overwrite all the files on the server with the new versions
 - Check 'config.template.php' for new values, and merge them into your 'config.php'
 - Check the 'custom_temlates/' directory for new templates, move and edit any that you find

== Custom Files

[horizontal]
'custom/ads.php'::
Included at the bottom of the claim page, for ads to be shown a ton of times.
'custom/ads_q.php'::
For &lsquo;quality&rsquo; ads &mdash; ads that shouldn&#700;t be shown on the automatic pages.
If an advertiser says that auto-refreshers aren&#700;t allowed, put their ad in this file instead of 'ads.php'.
'custom/claim_options.php'::
Extra form elements to add to the entry form on 'index.php'.
(Can be left empty.)
'custom/claim_options_process.php'::
For options that affect payout amounts. Included by 'faucet.php'.
(Can also be left empty.)
'custom/head.php'::
Included in the &lt;head&gt; tag of every page, for anti-adblock and link:https://www.internetdefenseleague.org[IDL scripts], google analytics, etc.
'custom/iframetraffic.php'::
Put sponsored sites here; it is included in the middle of the claim page.
'custom/navbar.php'::
This file contains the navbar at the top of most of the faucet pages.
You can add and remove links here.

== How to un-ban IP addresses

Open your '.htaccess' file and remove the line `deny from IP`, where *IP* is the IP address to un-ban.
